# La configuration github actions suivante est suffisante pour déclencher les tests à chaque push ou demande de fusion

name: CI

on: [ push, pull_request ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            - uses: php-actions/composer@v6
            - run: echo "Composer dependencies have been installed"
            # spécifie le fichier de configuration phpunit.xml à utiliser avec l'option -c (--configuration)
            - run: vendor/bin/phpunit --exclude-group functional-local
            # spécifie le fichier de configuration de codeception pour la CI de github action avec l'option -c
            - run: vendor/bin/codecept unit run -c github-codeception-config.yaml  --tests tests/Unit
